### ISSUE TITLE
'pcs resource agents systemd' does not list haproxy

### ISSUE THREAD

**Issue by rbjorklin** [ClusterLabs/pcs#108]
`pcs resource agents systemd` does not list haproxy service even though it is installed. This happens on CentOS 7. Running `pcs resource create LB systemd:haproxy op monitor interval=30s` still works but the service not being listed causes a bit of confusion. If this is already resolved in a newer version than I'm running please close this issue.

    pcs --version
    0.9.143

**Comment by tomjelinek** [comment]
Thank you for reporting this issue. It seems pacemaker is the component which need to be fixed in order to solve this. I filed a bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1382364 with more information about the issue. You can track progress there.

Closing this as this is most likely not pcs issue.

**Comment by celesteking** [comment]
systemctl enable haproxy
and it will be listed, but `resource describe` won't work

**Comment by rbjorklin** [comment]
@celesteking what if I want to have the service managed by pacemaker?

**Comment by tomjelinek** [comment]
`pcs resource describe` never worked for systemd agents as they do not provide metadata. It however works since https://github.com/ClusterLabs/pcs/commit/491ac087fd06480a9fda0dfc5dd97f6b9dfbae56.

Issue with haproxy not being listed need to be fixed in pacemaker as I mentioned before. For the time being you can use `pcs resource create --force`.
