### ISSUE TITLE
pcs status pcsd hanging

### ISSUE THREAD

**Issue by leavan126** [ClusterLabs/pcs#138]
I have an Asterisk cluster with two nodes that is running for a year now. Today I wanted to check the status of the cluster and it gives all the statuses except PCSD.... it just hangs forever, it was working fine last week. When I press CTRL+C it gives me two diffrent outputs on both nodes (see attached files) 
To me it looks like some authentication issue? (status = utils.checkAuthorization(node)

Everything works and I can pull status of everything except PCSD. I have tried google but doen't turn up anything. Help regarding this will be appriciated.

[node01.txt](https://github.com/ClusterLabs/pcs/files/1085583/node01.txt)
[node02.txt](https://github.com/ClusterLabs/pcs/files/1085584/node02.txt)

**Comment by tomjelinek** [comment]
Both the tracebacks are the same actually.

This doesn't look like an authentication issue to me. The `utils.checkAuthorization` function is used for checking if a remote pcsd is running and if it's authenticated. If there was an authentication problem, pcs would report it based on the value returned from the function.

It seems pcs is unable to connect to pcsd. However from the traceback it is not possible to see what the problem is. Is pcsd running on both nodes? Is it allowed in firewall? Is there an HTTPS proxy in the way?

You could also upgrade your pcs. Version 0.9.150 released upstream in April 2016 only prints pcsd status when `--full` is specified in the `pcs status` command. In version 0.9.156 from the beginning of 2017 pcs to pcsd communication was improved and the requests to check pcsd status timeout after a while. These of course don't fix your issue with pcs being unable to connect to pcsd, they just make `pcs status` work in those cases.

**Comment by leavan126** [comment]
Thank you for the quick reply!

I had a look if the services are running and it look fine ...
[pcsd.txt](https://github.com/ClusterLabs/pcs/files/1090633/pcsd.txt)

I have disabled the firewall on the heartbeat network as it has a direct cable connecting the two nodes.

I have scheduled an update for PCS when we have downtime on the 15th of July.
