### ISSUE TITLE
Disable resource monitoring on hosts?

### ISSUE THREAD

**Issue by aTanW** [ClusterLabs/pcs#156]
It is not an real issue, but more absent functionality report.

Example:

- two nodes A, B with full stack, two nodes X, Y with pacemaker_remote (actually LXC containeres)
- drbd on full stack nodes A, B controlled by pacemaker
- Filesystem on full stack nodes A, B controlled by pacemaker
- drbd resource location avoids X, Y
- colocation add Filesystem with drbd INFINITY

But cluster attempts to run monitor for drbd and Filesystem on X and Y.

Seems to me, it is not a normal situation.
IMHO, monitor operations must be run on candidate nodes, not on all available.

**Comment by tomjelinek** [comment]
This has nothing to do with pcs, it is completely on pacemaker side.

It is actually correct and perfectly normal. Pacemaker must run tests for the resources on those nodes to make sure the resources are not running there. If that bothers you, set resource-discovery in your location constraints. See [Location Properties in Pacemaker Explained](http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#_location_properties) for explanation and more details.

**Comment by aTanW** [comment]
> This has nothing to do with pcs, it is completely on pacemaker side.
I can not find "issues" in pacemaker project

> If that bothers you, set resource-discovery in your location constraints.
It shows errors in pcs status
Disabling resource-discovery disables it in whole cluster, or one node, but not on selection (in example X, Y) of nodes.

**Comment by tomjelinek** [comment]
Well, a simple location constraint applies to one node as well.

Alternatively you can use a location rule constraint. Either you make the rule match your node names or you set attributes for your remote nodes and match the rule against those attributes. Since you are concerned in distinguishing full-stack and remote nodes, you can use already existing attribute #kind provided by pacemaker as explained at [Built-in node attributes](http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html-single/Pacemaker_Explained/index.html#idm140583532691520).

It is better to ask this kind of questions at [ClusterLabs mailing list](http://oss.clusterlabs.org/mailman/listinfo/users) as they reach much broader audience there including pacemaker developers.

**Comment by aTanW** [comment]
Thank you. I found "whole" :) solution - "crm configure location/colocation" with sophisticated conditional rules.
