### ISSUE TITLE
make install_pcsd fails

### ISSUE THREAD

**Issue by chaoshr** [ClusterLabs/pcs#163]
Trying to setup corosync on CentOS 7-4.1708
Actual corosync repo version 2.4.0 loves to die with the following error: Connection to the CPG API failed: Library error (2) so I decided to compile the latest stable versions of corosync, pacemaker and pcs

make install_pcsd fails with a pretty useless error:
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://tojeline.fedorapeople.org/rubygems

bundle install --verbose reveals more details:
HTTP 404 Not Found https://tojeline.fedorapeople.org/rubygems/versions

Thoughts?

**Comment by tomjelinek** [comment]
https://tojeline.fedorapeople.org/rubygems hosts rpam-ruby19 rubygem tweaked for Ruby 1.8. Since CentOS 7 ships Ruby 2 so you do not need that gem at all. It has been removed from pcsd dependencies in https://github.com/ClusterLabs/pcs/commit/67675f33bb8ba21d9595272aa256684e04c1fa8c. Apply the commit or just use the latest master or 0.9 branch and you should be good.

**Comment by chaoshr** [comment]
Thx
