### ISSUE TITLE
Missing location for systemd units

### ISSUE THREAD

**Issue by kubikrobert** [ClusterLabs/pcs#164]
Similar to: https://github.com/ClusterLabs/pcs/issues/71

/lib/systemd/system is missing, fix:

```
if os.path.isfile("/etc/systemd/system/" + systemd_ra + ".service") or os.path.isfile("/usr/lib/systemd/system/" + systemd_ra + ".service") or os.path.isfile("/lib/systemd/system/" + systemd_ra + ".service"):
            return True
```

**Comment by tomjelinek** [comment]
This has been fixed a long time ago.

Since pcs 0.9.155, more specifically commit https://github.com/ClusterLabs/pcs/commit/491ac087fd06480a9fda0dfc5dd97f6b9dfbae56, pcs does not look for resource agents itself. Instead, it uses Pacemaker for accessing the agents. See also https://github.com/ClusterLabs/pcs/issues/81.
