### ISSUE TITLE
pcs cluster auth Access Denied

### ISSUE THREAD

**Issue by benknoble** [ClusterLabs/pcs#180]
Environment: Brand new CentOS7 VM (pcs 0.9.162)
Situation: Attempting to authenticate the VM with pcs, as it will be forming a cluster later (yet to set up nodes 2+).

It appears `pcs` is ignoring the provided username and password ?

```
[admin@host ~]$ pcs cluster auth $(hostname)
Username: hacluster
Password: ....

Please authenticate yourself to the local pcsd:
Username: hacluster
Password: ....

Error: Access denied
```

The relevant debug logs:

```
--Debug Input End--

Finished running: /usr/bin/ruby -I/usr/lib/pcsd/ /usr/lib/pcsd/pcsd-cli.rb auth
Return value: 0
--Debug Stdout Start--
{
  "status": "access_denied",
  "log": [
    "I, [2018-08-09T13:11:48.065643 #10637]  INFO -- : PCSD Debugging enabled\n",
    "D, [2018-08-09T13:11:48.065919 #10637] DEBUG -- : Did not detect RHEL 6\n",
    "D, [2018-08-09T13:11:48.065949 #10637] DEBUG -- : Detected systemd is in use\n",
    "I, [2018-08-09T13:11:48.129259 #10637]  INFO -- : Running: id -Gn admin\n",
    "I, [2018-08-09T13:11:48.129320 #10637]  INFO -- : CIB USER: hacluster, groups: \n",
    "D, [2018-08-09T13:11:48.131837 #10637] DEBUG -- : [\"nadmin wheel\\n\"]\n",
    "D, [2018-08-09T13:11:48.131904 #10637] DEBUG -- : []\n",
    "D, [2018-08-09T13:11:48.131929 #10637] DEBUG -- : Duration: 0.002502973s\n",
    "I, [2018-08-09T13:11:48.131972 #10637]  INFO -- : Return Value: 0\n",
    "I, [2018-08-09T13:11:48.132005 #10637]  INFO -- : Failed login by admin (user is not a member of haclient)\n"
  ]
}

--Debug Stdout End--
```

See how it thinks admin is logging in, and doesn't like that it doesn't belong to the group `haclient` ?

```
$ sudo -u hacluster groups
haclient
```

**Comment by ondrejmular** [comment]
Pcs is not ignoring specified username. It is checking the user as which you are executing a command (in your case it is user 'admin'). By default, only user 'hacluster' or users in group 'haclient' can interact with a cluster. This is the intentional behavior, so interaction with a cluster is consistent. Otherwise, some pcs commands may not work because of access checks within pacemaker.

We are aware of this unintuitive behavior, but it may be fixed only after changing to client-server architecture which is our long-term goal. In the meantime, you can add your 'admin' user to group 'haclient', or as you already know the password for 'hacluster', you can log in as 'halcuster' and run pcs commands as 'hacluster'.

**Comment by benknoble** [comment]
I see; thank you for the explanation @ondrejmular ; this was not clear following [Clusters from Scratch](http://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/1.1/html/Clusters_from_Scratch/_configure_corosync.html): could this be because in the example, `pcs auth` is executed by root ? If so, does that mean `sudo pcs auth` would do the trick ?

**Comment by ondrejmular** [comment]
You're right, all commands in Cluster from Scratch are executed by root. You can run `pcs auth` using `sudo` and it will work, but then you will have to use `sudo` basically for all `pcs` commands.

**Comment by benknoble** [comment]
Alright, thanks. Sounds like the most straightforward solution is being in the right group.
