### ISSUE TITLE
path to pacemaker related binaries is hardcoded

### ISSUE THREAD

**Issue by Thermi** [ClusterLabs/pcs#195]
Hello,

Currently, the path to the pacemaker related binaries is hardcoded in `pcs/settings_default.py` (the settings of pcs are then loaded in pcs/settings.py without any existing way of changing them) as `/usr/libexec/pacemaker`. On some distributions, such as Arch Linux, the `/usr/libexec/` directory does not exist. Instead, the files are moved to, for example, `/usr/lib/pacemaker/`. Because the paths are hardcoded, most of the commands of pcs fail on such hosts, because the paths are wrong.
Replacing the paths in the settings file with `sed` is a possible solution, but a host-variable path would be nice. Or at least a native way to change them, for example, during build time with a flag, like the ones already implemented in the Makefile.

E.g.
```
pcs property set stonith-enabled=false
Error: unable to run command /usr/libexec/pacemaker/pacemaker-schedulerd metadata: No such file or directory: '/usr/libexec/pacemaker/pacemaker-schedulerd'
```

**Comment by jnpkrn** [comment]
Sorry for a possibly overboard complication, but the ultimate solution
is for `pcs` to call (or perform directly if there are suitable
libraries for that -- note that the format is straightforward enough
to crank up a custom parser in a minute):
`pkg-config --variable=daemondir pacemaker`

Indeed, for upstream-based RPM packaging, it means that pcs would
need to require `pacemaker-libs-devel`.  One could argue, that
`pacemaker.pc` shall rather be installed with base `pacemaker`
packages, since that file contains multiple very useful configuration
specific data usable outside of build purposes.
Let me know if such a change in pacemaker would be desired.

**Comment by tomjelinek** [comment]
There is a way for changing the paths (or any value in `pcs/settings.py`) during build time. Debian is making use of that, see `pcs/settings.py.debian` and `pcsd/settings.rb.debian` files and `use-alternative-file` in `Makefile`.

If you provide a pull request adding similar support for Arch, I'll be happy to review it.

**Comment by tomjelinek** [comment]
Hi,

the whole `pcs` building process has been overhauled recently. Now, it makes use of `autotools` and therefore it should be able to autodetect paths to various files `pcs` depends on, including `pacemaker` binaries and data files, `python` binaries and so on. It is going to be released in the next version of `pcs`. Feel free to take a look at it and report back if it fixes your issue or not. You can find a short tutorial for the new building process in the `CONTRIBUTING.md` file.
