### ISSUE TITLE
Trying to force python 3.5 version on pcs

### ISSUE THREAD

**Issue by dviljoen** [ClusterLabs/pcs#203]
Trying to write a custom fencing agent in python 3.5 that uses our existing modules.  But when pcs executes our agent it fails because it is using 3.4.  Logging sys.path gives:
2019-04-25 18:19:34,883 DEBUG sys.path: /usr/sbin
2019-04-25 18:19:34,883 DEBUG sys.path: /usr/lib/python3.4
2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3.4/plat-x86_64-linux-gnu
2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3.4/lib-dynload
2019-04-25 18:19:34,884 DEBUG sys.path: /usr/local/lib/python3.4/dist-packages
2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3/dist-packages

I've built everything from source on a Ubuntu 14.04 system and created a debian package with checkinstall.  pcs itself seems to run just fine.  Running my fence agent from the command line works just fine.  However, my agent cannot be run from pcs when I (e.g.) run: pcs stonith list.

If I remove all references to our modules, pcs is able to run it no problem.  

So far I have attempted to add python_requires=">=3.5" to the setup.py.  While this appears to get pcs to execute using python 3.5, it cannot resolve the pcs module.  Weirdly, the module is installed under /usr/local/lib/python3.5/site-packages.

Any help would be appreciated.

**Comment by dviljoen** [comment]
An update: looking more closely at the debian package generated with the python_requires flag set, it didn't actually include any of the python code into the final package.  Not sure why.  creating the package without that flag includes everything.

**Comment by tomjelinek** [comment]
I don't quite understand if you have problem with running pcs or your agent.

> But when pcs executes our agent it fails because it is using 3.4.

What is using Python 3.4? Pcs or your fence agent? Is it wrong that 3.4 is used? Why?

> Logging sys.path gives:
> 2019-04-25 18:19:34,883 DEBUG sys.path: /usr/sbin
> 2019-04-25 18:19:34,883 DEBUG sys.path: /usr/lib/python3.4
> 2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3.4/plat-x86_64-linux-gnu
> 2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3.4/lib-dynload
> 2019-04-25 18:19:34,884 DEBUG sys.path: /usr/local/lib/python3.4/dist-packages
> 2019-04-25 18:19:34,884 DEBUG sys.path: /usr/lib/python3/dist-packages

Is this from pcs or your agent?

> pcs itself seems to run just fine. Running my fence agent from the command line works just fine.

How do you run them?

> However, my agent cannot be run from pcs when I (e.g.) run: pcs stonith list.

What does "cannot be run" mean? Any debug logs, `pcs stonith list --debug`, `pcs stonith describe <your agent> --debug`? Is your agent listed in `crm_resource --list-agents stonith`?

Note pcs is never running fence (and resource) agents itself. Pcs runs pacemaker tools which run the agents. Pcs can happily use different Python version than your agent since they are two separate processes. You can have agents written in languages other than Python, too.

**Comment by dviljoen** [comment]
Sorry for not being more clear.  We do our development in python 3.5.  Our modules are all in python 3.5.  I created an agent in python 3.5.  When I run crm_resource --list-agents my agent shows up.  

$ sudo crm_resource --list-agents stonith
fence_pcmk
fence_legacy
fence_firefly  <--- my agent

When I run pcs stonith list it was not showing up.  (in fact, none were)

$ sudo pcs stonith list
Error: No stonith agents available. Do you have fence agents installed?

Running from the command line:

$ echo "action=metadata" | fence_firefly
<?xml version="1.0" ?>...

Same for the other two agents.  But in my logging I dumped out the sys.path values and could see that when my agent gets called from $ pcs stonith list my paths are all for python 3.4 and it can't find my modules.  What is weird is that when I run:

$ sudo crm_resource --show-metadata stonith:fence_firefly
<resource-agent name="fence_firefly" shortdesc="Fence agent for FireFly database">...

It returns my metadata, (without the <?xml...> header) and according to my log file it never actually executed my agent.  So I'm guessing that it has it cached somewhere.

Is that more clear?

**Comment by dviljoen** [comment]
And here's the debug output:
$ sudo pcs stonith list --debug
Running: /usr/sbin/crm_resource --list-agents stonith
Environment:
  LC_ALL=C

Finished running: /usr/sbin/crm_resource --list-agents stonith
Return value: 0
--Debug Stdout Start--
fence_pcmk
fence_legacy
fence_firefly

--Debug Stdout End--
--Debug Stderr Start--

--Debug Stderr End--

Running: /usr/sbin/crm_resource --show-metadata stonith:fence_firefly
Environment:
  LC_ALL=C
  PATH=/usr/sbin/:/bin/:/usr/bin/

Finished running: /usr/sbin/crm_resource --show-metadata stonith:fence_firefly
Return value: 5
--Debug Stdout Start--

--Debug Stdout End--
--Debug Stderr Start--
Metadata query for stonith:fence_firefly failed: -5

--Debug Stderr End--

Error: No stonith agents available. Do you have fence agents installed?

**Comment by dviljoen** [comment]
There is a permissions problem.  If I run without sudo:

$ crm_resource --show-metadata stonith:fence_firefly
Metadata query for stonith:fence_firefly failed: -5

**Comment by dviljoen** [comment]
One more data point to consider.  Logging the sys.path values:

Running from pcs stonith list:
2019-04-26 12:59:33,656 DEBUG --------- fence_firefly invoked ----------
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/sbin
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/lib/python3.4
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/lib/python3.4/plat-x86_64-linux-gnu
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/lib/python3.4/lib-dynload
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/local/lib/python3.4/dist-packages
2019-04-26 12:59:33,657 DEBUG sys.path: /usr/lib/python3/dist-packages

Running from crm_resource directly:
2019-04-26 13:17:03,696 DEBUG --------- fence_firefly invoked ----------
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/sbin
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/local/lib/python35.zip
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/local/lib/python3.5
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/local/lib/python3.5/plat-linux
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/local/lib/python3.5/lib-dynload
2019-04-26 13:17:03,696 DEBUG sys.path: /usr/local/lib/python3.5/site-packages
2019-04-26 13:17:03,696 DEBUG sys.path: /mnt/shared/-w/firefly/inara/vendor/redis-py
2019-04-26 13:17:03,697 DEBUG sys.path: /mnt/shared/-w/firefly/inara/vendor/apache-libcloud
2019-04-26 13:17:03,697 DEBUG sys.path: /mnt/shared/-w/firefly/inara/vendor/debinterface
2019-04-26 13:17:03,697 DEBUG sys.path: /mnt/shared/-w/firefly/inara/python
2019-04-26 13:17:03,697 DEBUG sys.path: /mnt/shared/-w/firefly/inara/infiniview

**Comment by tomjelinek** [comment]
It looks like you have some environment settings in place which make your agent run with custom (not coming from your Linux distro) python version (pyenv or similar). Since pcs does not pass environment variables to processes it runs, this won't work.

The bigger issue is that when pacemaker will run your fence agent in a live cluster, it most probably won't pass such settings to it anyway. You should modify your agent to be able to run without any extra environment settings.

**Comment by dviljoen** [comment]
I don't know if you followed what I posted carefully enough.  When crm_resource runs my fence agent, it works.  Python3.5 IS my default python.  Root uses it. All of the user accounts use it.  There's no special magic going on in my login.  But when pcs calls crm it fails with the wrong environment.  Its not that pcs is doing the standard thing and my stuff is doing something non-standard.  its the other way around.

**Comment by dviljoen** [comment]
The best clue to my mind is the above output I shared where I ran crm_resource without sudo.  It gives the same error that pcs gives.  Even though I'm running pcs with sudo, it seems to be running the fence agent with some degraded permissions.

**Comment by tomjelinek** [comment]
I did follow carefully what you posted. But I am not sitting at your machine. I can only work with information you provided and you have not provided much. I do not know how your machine is set, how you made python 3.5 your default python (/usr/local/lib/python3.5 doesn't come from your distro, does it?), what is your fence agent's shebang, what are your environment variables (pcs does not pass them to crm_resource), does it work when you run `pcs stonith list` as root (not using sudo), what permissions are set on your agent (since you think it's a permission problem), what pcs version you use, ...

Note that running crm_resource from command line with your environment is not the same as when pacemaker daemon runs it with completely different environment.

**Comment by tomjelinek** [comment]
@dviljoen Are you willing to share details about your setup so that we can reproduce the issue?
