### ISSUE TITLE
[no-effect problem] pcs does not take `maintenance` meta-attribute for resources into account

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/pcs#234]
For example, one may expect that `pcs resource manage` would bring
the resource to work as usual, but it may not be the case when it
at the same time carried `maintenance` meta-attribute set to positive.
In such a case, that shall be droped from configuration as well.

In general, this means that pcs shall make some new precautions about
`manage` and `unmanage` actions applied to resources so as to avoid
no-effect problem.  I think turning `--monitor` modifier to boil down
to that new multi-toggle is unjustifiable (just as I think the same
about adding it to pacemaker originally = that "simplification" just
complicated the life of pcs, cf. this very issue).

TBH, didn't know about that possibility back then:
https://bugzilla.redhat.com/show_bug.cgi?id=1303969

References:
https://lists.clusterlabs.org/pipermail/developers/2019-December/002244.html
https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html-single/Pacemaker_Explained/index.html#_resource_meta_attributes

* * *

Similarly, but with a different resolution for apparent reasons (no 1:1)
there could be a warning if there are any/all nodes in maintenance mode
-- especially if they happen to posses running instances of given resource
in the current in-maintenance snapshot/s -- since the command won't have
an immediate effect either (just after putting the node/s out of
maintenance).

**Comment by tomjelinek** [comment]
The `pcs resource manage` command sets and unsets the `is-managed` meta-attribute of a resource. If unsetting the meta-attribute has no effect because there is another piece of configuration in place (maintenance mode set on a node, maintenance meta-attribute, resource defaults, etc.), the user must figure that out and decide what to do. If pcs was to automatically check these places and change their settings, it would more likely than not break some potentially complex or important configuration set in place by the user.
