### ISSUE TITLE
Replace Thin by Puma

### ISSUE THREAD

**Issue by voxik** [ClusterLabs/pcs#264]
Have you considered to replace Thin by Puma? My main motivation for this question is that pcs is almost the last package in Fedora, which requires Thin for its functionality. Part of the reasons is that Puma is these days preferred choice for Ruby on Rails and therefore it gets more developer attention.

**Comment by tomjelinek** [comment]
We are working on moving all functionality currently implemented in legacy parts written in Ruby to Python. Once that's done, there will be no Ruby code in pcs and no need for Thin nor Puma. If pcs depending on Thin is a problem in the meantime, we can bundle it in pcs rpm.

**Comment by lucaskanashiro** [comment]
@tomjelinek is there a timeline to move `pcsd` to python? Any WIP branch?

**Comment by tomjelinek** [comment]
There is no timeline and no WIP branch. The amount of ruby code is rather big and the key components are rather complex. Instead of having one WIP branch, we are creating branches for moving specific parts of pcsd to python and merging them to main branch. Recently, we moved a request processor and authentication to python: https://github.com/ClusterLabs/pcs/commit/fd2312b4bc94ddc2af3f3d663670a456a400df5e
