### ISSUE TITLE
pcs AWS elastic IP resource not starting

### ISSUE THREAD

**Issue by hiranthaPeiris** [ClusterLabs/pcs#374]
Hi,

I have been trying to create an HA cluster with pacemaker on aws EC2 instances but I keep getting my elastic IP into stopped state.
what I have done for now:
* configured aws cli
* set default profile
* set no-quorum-policy=ignore
* set stonith-enabled=false
* set IAM role with EC2 permissions 

Both EC2 instances have subnet auto assigned public ips and the eip I am trying is available to assign.  

Here is a screen shot of pcs status
![pcs-st](https://user-images.githubusercontent.com/27503578/132651761-c1cbdedd-484b-4595-8da0-7d7c43d62607.PNG)

after further looking in i found this on pcs logs
![aws-pcs](https://user-images.githubusercontent.com/27503578/132651880-3736e652-634f-461e-a315-aeaf81135530.PNG)
It says `elastic_start_0:1538:stderr [ The config profile (default) could not be found ]`

what could be the reason for this. any help will be appreciated.

**Comment by tomjelinek** [comment]
Hi,

This seems to be either a configuration or aws specific issue rather than a pcs one. Please, post your question to [users@clusterlabs.org mailinglist](https://lists.clusterlabs.org/mailman/listinfo/users) so that it reaches a wider audience. There is a higher chance to reach someone who has experience with aws and can help you with this issue.

Thank you,
Tomas
