### ISSUE TITLE
Error: Agent 'ocf:linbit:drbd' is not installed or does not provide valid metadata: Element content failed to validate content, line 117, use --force to override

### ISSUE THREAD

**Issue by MarkLTZ** [ClusterLabs/pcs#441]
Description of problem:

Configuring DRBD on Pacemaker cluster I got this error:

[root@node1 setup]# pcs resource create drbd ocf:linbit:drbd drbd_resource=resource0 promotable promoted-max=1 promoted-node-max=1 clone-max=3 clone-node-max=1 notify=true 
Error: Agent 'ocf:linbit:drbd' is not installed or does not provide valid metadata: Element content failed to validate content, line 117, use --force to override
Error: Errors have occurred, therefore pcs is unable to continue

Version-Release number of selected component (if applicable):

[root@node1 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

[root@node1 ~]# rpm -q pcs
pcs-0.10.12-1.el8.x86_64       

[root@node1 ~]# rpm -q drbd
drbd90-utils-9.19.1-1.el8.elrepo.x86_64

How reproducible:

[root@node1 ~]# pcs resource create drbd ocf:linbit:drbd drbd_resource=resource0 promotable promoted-max=1 promoted-node-max=1 clone-max=3 clone-node-max=1 notify=true 

Steps to Reproduce:
1. Install new CentOS Stream 8 server
2. Install and configure drbd
3. Install pacemaker
4. Try to configure drbd resource

Actual results:

Error: Agent 'ocf:linbit:drbd' is not installed or does not provide valid metadata: Element content failed to validate content, line 117, use --force to override
Error: Errors have occurred, therefore pcs is unable to continue

Expected results:

Cluster resource created.

Additional info:

Downgrading to pcs-0.10.11-1.el8 the issue is not present.

**Comment by tomjelinek** [comment]
pcs-0.10.12 adds support for OCF 1.1 resource agents. In order to be able to distinguish OCF 1.0 and OCF 1.1 agents and process them correctly, pcs validates agents' metadata against OCF schema. This prevents pcs from crashing due to accessing missing parts of metadata which are mandatory by the standard yet missing in the actual agent not complying to the standard.

The drbd agent specifies `<content type="numeric"/>` for parameter `wfc_timeout`. This is not in compliance with OCF 1.0 standard and therefore pcs is right to produce an error. However, this violation is insignificant to pcs, therefore I'm going to relax the validation to make pcs compatible with the existing drbd agent.

**Comment by tomjelinek** [comment]
resolved by #443 and #442
