### ISSUE TITLE
Can't add a node to cluster

### ISSUE THREAD

**Issue by Tsunani** [ClusterLabs/pcs#461]
Hello all.
After create cluster i remove node. And i can't add new to cluster.
`pcs cluster node add newdirdb1`

```
No addresses specified for host 'newdirdb1', using 'newdirdb1'
No watchdog has been specified for node 'newdirdb1'. Using default watchdog '/dev/watchdog'
Error: Cluster uses SBD with shared storage so SBD devices must be specified for all nodes, no device specified for node 'newdirdb1'
Running SBD pre-enabling checks...
newdirdb1: SBD pre-enabling checks done
Error: Errors have occurred, therefore pcs is unable to continue
```

I ask for help.

**Comment by tomjelinek** [comment]
Hi,

Based on the error message, it seems the cluster has been configured to use SBD with devices. In that case, all nodes must have access to all SBD devices used by the cluster. Since you have not specified any SBD devices in the `pcs cluster node add` command, pcs refuses to add the node to the cluster.

If you run `pcs cluster node add -h`, you'll get help for the command including syntax for specifying SBD devices (and SBD watchdog in case the default `/dev/watchdog` doesn't fit your environment).

You can run `pcs stonith sbd config` to display SBD configuration including number of SBD devices used.
