### ISSUE TITLE
possible copy paste error

### ISSUE THREAD

**Issue by eslerm** [ClusterLabs/pcs#645]
In [pcs/cli/common/parse_args.py's InputModifiers.get()](https://github.com/ClusterLabs/pcs/blob/f72d5dd8c7f79941daa45e0653ea23d60ab999b6/pcs/cli/common/parse_args.py#L638) the wrong option might be being returned.

Should:
```
        if option in self._defined_options:
            return self._options[option]
````

Be:
```
        if option in self._defined_options:
            return self._defined_options[option]
```

**Comment by ondrejmular** [comment]
Thanks for reporting this. However, there is no issue in the code you are mentioning. `self._defined_options` is set of strings where all options specified by user are stored. In `self._options` all options (including specified by user and global defaults) and their values are stored. Therefore if the option was specified by the user, its value is returned, otherwise default value is returned (this is handled below the code you are referring to).
