### ISSUE TITLE
CentOS 6 x64 cluster configuration problems.

### ISSUE THREAD

**Issue by VolodyaIvanets** [ClusterLabs/pcs#91]
Hello,

I'm trying to configure test cluster on CentOS 6 x64. I've installed Corosync and Pacemaker from sources. PCS version 0.9.139-9 was installed using yum.

I am not able to create cluster. I executed _pcs cluster auth_:

```
[root@node-1 src]# pcs cluster auth 192.168.0.10 192.168.0.20 192.168.0.30 192.168.0.40
Username: hacluster
Password:
Error: 192.168.0.10: Unable to connect to pcsd: Error connecting to 192.168.0.10 - (HTTP error: 500)
Error: 192.168.0.20: Unable to connect to pcsd: Error connecting to 192.168.0.20 - (HTTP error: 500)
Error: 192.168.0.30: Unable to connect to pcsd: Error connecting to 192.168.0.30 - (HTTP error: 500)
Error: 192.168.0.40: Unable to connect to pcsd: Error connecting to 192.168.0.40 - (HTTP error: 500)
```

https://192.168.0.10:2224/login (as well as all other servers) shows application error:
**Errno::ENOENT at /login
No such file or directory - /usr/sbin/corosync-objctl**

I've then created symbolic link **/usr/sbin/corosync-objctl -> /usr/sbin/corosync-cmapctl** on every machine and cluster authentication went fine.

When I tried to run _pcs cluster setup_ I got this:

```
[root@node-1 src]# pcs cluster setup --name hacluster 192.168.0.10 192.168.0.20 192.168.0.30 192.168.0.40 --force
Error connecting to 192.168.0.10 - (HTTP error: 500)
Error: Unable to set cluster.conf
```

So I checked https://192.168.0.10:2224/login again and saw **PCSD GUI is disabled** message.

I have the same installation working fine on CentOS 7. I will appreciate any hints.

Thanks a lot!

**Comment by tomjelinek** [comment]
Hello,

It looks like you're using corosync 2. Pcs 0.9.139 expects corosync 1 to be installed when running on CentOS 6. That's why everything works for you on CentOS 7. There are two ways to solve your issue. You can either install pacemaker and corosync using yum, so you get corosync 1. Or you can install pcs 0.9.145 or newer from sources, which detects corosync version correctly.

Web UI is disabled by default in CentOS 6 rpm package. You can enable web UI in `/etc/sysconfig/pcsd` but there may be issues with it. 

Also note the symbolic link you created cannot really work as there are significant differences between corosync-objctl and corosync-cmapctl.

**Comment by VolodyaIvanets** [comment]
Hello sir,

I'll definitely try newer version of pcs when will have a chance and provide update.

Thank you!

**Comment by VolodyaIvanets** [comment]
Hello,

So I was able to make PCS 0.9.139 work with Corosync 1 on CentOS 6.
I was also trying to install latest PCS (which is 0.9.150 at the moment). During attempt of fixing dependencies, I found this article [https://halessonslearned.wordpress.com/2013/05/17/tips-linux-ha-cluster-on-rhel-6-the-cluster-components/](url). Could someone please tell me if there are cases where people are running Corosync 2 successfully on CentOS 6?

Thanks!

**Comment by tomjelinek** [comment]
Hello,

It's better to ask questions like this on users@clusterlabs.org mailing list or check its archives. You may find more info about the list at http://clusterlabs.org/wiki/Mailing_lists.

Hope that helps.

**Comment by VolodyaIvanets** [comment]
Hi Tom,

Thank you very much!
